Lecture 10: Sequential models
sailinglab/pgm-spring-2019 pull request #11
Opened 2019-02-23 21:54 UTC by abhimohta

https://abhimohta.github.io/pgm-spring-2019/notes/lecture-10/

2019-03-01 05:18 UTC, abhimohta commented
When can we expect the review?

2019-03-01 05:46 UTC, alshedivat commented
@zhisbug, can you take a look? Thanks!

2019-03-04 20:17 UTC, zhisbug requested changes
@abhimohta  @iedwardwangi  @alankarj 
Despite a few minor problems I have spotted, this is a great scribe note.
Please address my comments and I'll take a second review before merging.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +P(X | \mu, \Sigma) = \frac{1}{(2\pi)^{n/2} |\Sigma|^{1/2}} exp(\frac{-1}{2}(X - \mu)^{T}\Sigma^{-1}(X-\mu))
use $\exp$ instead of raw text $exp$ in a math env.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +\begin{aligned}
Make this left aligned using &.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +			P(X) = \mathcal{N}(X;0, I) \\
make this left aligned.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +			Cov[X, Y] = E[(X - 0)(Y - \mu)^T] = E[X(\mu + \Lambda X + W -\mu)^T] \\
This one looks great.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +		\Sigma_{11} = I \\
left aligned.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +since the posterior covariance ($V_{1|2}$ above) and does not depend on the observed
since the posterior covariance ($V_{1|2}$ above) and does not depend on the observed
-> since the posterior covariance ($V_{1|2}$ above) does not depend on the observed

an extra `and`?

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +\begin{aligned}
Align at the `=` is also fine. Make sure your way of alignment is consistent across the notes.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +x_t &= f(x_{t-1}) + G w_t \\
Are you sure the equations here are correct? It seems to me there is no connections between x and y from these equations...

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +x_t &= Ax_{t-1} + G w_t \\
Same here

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +where $K_{t+1}  = P_{t+1\|t}C^T(CP_{t+1\|t}C^T+R)^{-1}$ is reffered to as the Kalman gain matrix.
typo: reffered

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +	\begin{aligned}
This alignment looks great.

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +m = \begin{bmatrix} \hat{x}_{t|t} \\ \hat{x}_{t+1|t} \end{bmatrix}, V = \begin{bmatrix} P_{t|t} & P_{t|t}A^T \\ AP_{t|t} & P_{t+1|t} \end{bmatrix}
what are m and V here?

2019-03-04 20:17 UTC, zhisbug commented on _posts/2019-02-18-lecture-10.md
> +	& = f_1(X_1,\sum_0) + f2(\{X_tX_{t-1}^T, X_tX_t^T,X_t:\forall t \};A,Q,G) + f3(\{X_tX_t^T,X_t : \forall t\};C,R)
f2 and f3 are not properly formatted here... Please fix.

2019-03-06 20:30 UTC, abhimohta commented
@zhisbug the requested changes have been made. Can you please have a look?

2019-03-22 16:36 UTC, zhisbug commented
LGTM, I will make the merge.

2019-03-22 16:36 UTC, zhisbug approved these changes

2019-03-22 16:37 UTC, merged