Lecture #17 (Eric):  Deep generative models (part 1)
sailinglab/pgm-spring-2019 pull request #20
Opened 2019-03-27 20:20 UTC by ThitherShore

preview link: https://thithershore.github.io/pgm-spring-2019/notes/lecture-17/
Thanks!

2019-04-09 01:56 UTC, alshedivat requested changes
Looks like a great set of notes. Thanks for the effort!

One minor change and ready to merge: The citations seem to not display correctly. Could you please convert citations to a proper format using `<d-cite></d-cite>` tags? Please make sure all referred work is cited Thanks.

2019-04-15 17:23 UTC, alshedivat commented
@ThitherShore, could you please address the feedback, so we can merge? Thanks!

2019-04-17 16:55 UTC, ThitherShore commented
> @ThitherShore, could you please address the feedback, so we can merge? Thanks!
I should have noticed this issue earlier... but citation tags have been updated now.
I am sorry for the delay, and we appreciate your time for reviewing! : D

2019-04-17 16:59 UTC, alshedivat approved these changes

2019-04-17 16:59 UTC, merged