lecture 18: Deep Generative Models (Part 2) -- v1
sailinglab/pgm-spring-2019 pull request #21
Opened 2019-04-02 05:11 UTC by RifleZhang

Link preview: https://riflezhang.github.io/pgm-spring-2019/notes/lecture-18/
I submitted the first version of lecture 18 scribing.
Thanks for revision!

2019-04-03 17:26 UTC, lileee commented
Thanks for the first draft of notes.

The content looks good, but could you format the scribe notes in paragraph form so that it reads more like a blog post, rather than bullet points from lecture slides.

Here's an example that I liked: https://sailinglab.github.io/pgm-spring-2019/notes/lecture-13/

2019-04-17 17:13 UTC, RLAgent requested changes
Thanks for the updated notes!

I addressed some grammatical issues here: https://github.com/sailinglab/pgm-spring-2019/pull/21/files#diff-7130e1985c0ff084366496441af74cb8

It looks like "Integrating domain knowledge in DL" is still in bullet points, so could you ping me when this is changed.

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +The **descriminative** part of GAN tells apart the true data distibution from the generated distribution. Specifically, the descrimination $D_\phi (x)$ outputs a probability of $x$ being the true dat
Spelling: "discriminative"

```suggestion
The **discriminative** part of GAN tells apart the true data distribution from the generated distribution. Specifically, the discriminator $D_\phi (x)$ outputs a probability of $x$ being the true data.
```

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +From 2014 to 2018, GAN can generate more high quality and more realistic images.
```suggestion
Between 2014 and 2018, GAN has progressively been able to generate more high quality and more realistic images.
```

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +In GAN setting, we have a generative model and a discriminator model. The generative model trys to generate new data given a prior,
```suggestion
In the GAN setting, we have a generative model and a discriminator model. The generative model tries to generate new data given a prior, 
```

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +It defines a implicit distribution over $x: p_{g_\theta}(x)$, and uses a stochastic process to simulate data $x$. It is intractable to evaluate the likelihood of generated data.
```suggestion
It defines an implicit distribution over $x: p_{g_\theta}(x)$, and uses a stochastic process to simulate data $x$. It is intractable to evaluate the likelihood of the generated data.
```

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +In order to solve the problem, **WGAN** <d-cite key="wgan"></d-cite> was proposed, in which a new objective was used by changing the distance function to Wasserstein Distance(Earth Mover). It measure
```suggestion
In order to solve the problem, **WGAN** <d-cite key="wgan"></d-cite> was proposed, in which a new objective was used by changing the distance function to Wasserstein Distance (Earth Mover). It measures the minimum transportation cost for making one pile of dirt in the shape of one probability distribution to the shape of the other distribution.
```

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +During the training, we compare the GAN discriminator with the WGAN critic when learning to differentiate two Gaussians. As we can see, the traditional GAN
```suggestion
During training, we compare the GAN discriminator with the WGAN critic when learning to differentiate between two Gaussians. As we can see, the traditional GAN
```

2019-04-17 17:13 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +Although GAN can produce sharp images, in most of the cases those images are in small resolutions with limited variation. Directly generating large image is impractable because the training becomes u
```suggestion
Although GAN can produce sharp images, in most cases, the images are in small resolutions with limited variation. Directly generating large image is impractical due to training instability. Due to those problems, the **Progressive GAN** <d-cite key="pgan"></d-cite> was proposed to improve the training method for large images. 
```

2019-04-23 13:33 UTC, alshedivat commented
@lileee, @RifleZhang, just checking in to see if these notes are ready to be merged. Thanks.

Btw, the first image in the notes is pretty low resolution (which kind of defeats the point :)). How about using [this one](https://pbs.twimg.com/media/Dw6ZIOlX4AMKL9J.jpg) instead?

2019-04-23 13:37 UTC, alshedivat commented
After a quick look, seems like "Learning with constraints" section needs another pass (basically, convert bullet points to text). Minor: the reference under the GLOW samples image is plain text -- could you make it `<d-cite></d-cite>` type of reference?

2019-04-26 22:35 UTC, RifleZhang commented
Will address the problems soon.
Thanks!

On Tue, Apr 23, 2019 at 9:37 AM Maruan <notifications@github.com> wrote:

> After a quick look, seems like "Learning with constraints" section needs
> another pass (basically, convert bullet points to text). Minor: the
> reference under the GLOW samples image is plain text -- could you make it
> <d-cite></d-cite> type of reference?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sailinglab/pgm-spring-2019/pull/21#issuecomment-485805986>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACUCXZ4VFYRQXTF7YAC5AVLPR4GH7ANCNFSM4HC4T6PQ>
> .
>

2019-04-29 21:15 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +## Learning with Constraint
```suggestion
## Learning with Constraints
```

2019-04-29 21:16 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +In the previous sections, the propsed model has two parts: a deep generative model and a knowledge constraint model. In the optimization step, we should have a regular generative objective $\mathcal{
```suggestion
In the previous sections, the proposed model has two parts: a deep generative model and a knowledge constraint model. In the optimization step, we should have a regular generative objective $\mathcal{L}(\theta)$, and a constraint regularization expectation $E_{p_\theta}[f(x)]$. We put them together, the objective is simply:
```

2019-04-29 21:16 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +In general,$E_{p_\theta}[f(x)]$ is hard to optimize unless $p_\theta$ is a GAN-like implicit generative model or an explicit distribution that can be efficiently reparametrized.
```suggestion
In general, $E_{p_\theta}[f(x)]$ is hard to optimize unless $p_\theta$ is a GAN-like implicit generative model or an explicit distribution that can be efficiently reparametrized.
```

2019-04-29 21:17 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +### Wasserstein GAN(WGAN)
```suggestion
### Wasserstein GAN (WGAN)
```

2019-04-29 21:18 UTC, lileee commented on _posts/2019-03-25-lecture-18.md
> +The optimization problem could be solve by EM algorithm.
```suggestion
The optimization problem can be solve by EM algorithm:
```

2019-04-29 21:20 UTC, RLAgent requested changes
The notes look good, thanks!

I made minor grammatical error comments here: https://github.com/sailinglab/pgm-spring-2019/pull/21/files#diff-7130e1985c0ff084366496441af74cb8

Could you address them, then we can merge the notes to master. Thanks!

2019-05-03 14:40 UTC, RifleZhang commented
Dear Lisa,

The changes are merged. Is there anything else to address before merging?
Thanks!

Best,
Ruohong

On Mon, Apr 29, 2019 at 5:20 PM Lisa Lee <notifications@github.com> wrote:

> *@lileee* requested changes on this pull request.
>
> The notes look good, thanks!
>
> I made minor grammatical error comments here:
> https://github.com/sailinglab/pgm-spring-2019/pull/21/files#diff-7130e1985c0ff084366496441af74cb8
>
> Could you address them, then we can merge the notes to master. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sailinglab/pgm-spring-2019/pull/21#pullrequestreview-231908876>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACUCXZ2EZY6XZG3TJA3TRPDPS5RC3ANCNFSM4HC4T6PQ>
> .
>

2019-05-09 14:59 UTC, merged