Lecture 25 notes
sailinglab/pgm-spring-2019 pull request #33
Opened 2019-04-25 18:43 UTC by xiamengzhou

2019-05-05 21:32 UTC, zhisbug commented
@xiamengzhou : could you provide a link to the rendered version so that I can review? Thanks!

2019-05-05 22:11 UTC, xiamengzhou commented
Sure, here is the link!
https://xiamengzhou.github.io/pgm-spring-2019/notes/lecture-25/

2019-05-06 00:46 UTC, zhisbug requested changes
Please address my comments and I'll take a second review.

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +However, if look at a simple latent variable model with one hidden, and 3 observed states depending on that hidden state, we can see that there is a relationship between the number of hidden states f
if look at -> if looking at

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +If we have 1 state, then the marginalized distribution is equal to the conditional distribution of the observed variables on $H$, which means they're all independent. On the other hand if $H$ has $m^
marginalized -> marginal

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +If we have 1 state, then the marginalized distribution is equal to the conditional distribution of the observed variables on $H$, which means they're all independent. On the other hand if $H$ has $m^
Typo: wher?

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +If we have 1 state, then the marginalized distribution is equal to the conditional distribution of the observed variables on $H$, which means they're all independent. On the other hand if $H$ has $m^
$m$ is number of ... -> $m$ is the number of ...

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +### Matrix view of probability rules
-> A matrix view of ...

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +#### Two variable example
example -> examples

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +We know that $$ \mathcal{P}[A, B] = \mathcal{P}[A\mid X]\mathcal{P}[X]\mathcal{P}[B\mid X]^T $$ We also note that each of these factor matrices have rank $\leq k$, which means that matrix characteriz
please reformat this sentence as it looks not properly formatted.

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +Thus, we can see that latent variable models encode *low rank dependencies* among variables, and we can our linear algebra toolkit to exploit the low rank structure.
missing a verb?

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +$$ \mathcal{P}[X_{\{1,2\}}, X_{\{3,4\}}] = \mathcal{P}[X_{\{1,2\}} | H_2] \mathcal{P}[\oslash H_2]\mathcal{P}[X_{\{3,4\}}|H_2]^T$$
what does $\oslash$ mean here? better give some context.

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +$$\mathcal{P}[X_{\{1,2\}} | H_2] \mathcal{P}[\oslash H_2]\mathcal{P}[X_{\{3,4\}}|H_2]^T = \mathcal{P}[X_{\{1,2\}}, X_{\{3,4\}}]$$
Align the two equations below?

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +which gives a factorization that only contains observed variables, indicating there is no need to learn latent variables using EM, hence more efficient an no local optimal problem. The caveat is that
-> hence it is more efficient and has no problem of reaching local optima.

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +we can simply obtain MLE of the matrices on the right hand side by the counting from samples.
-> by counting from samples (remove "the")

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +This is much more difficult to fix, and intuitively corresponds to how the problem becomes intractable if $k >> m$.
the condition after "if" is missing.

2019-05-06 00:46 UTC, zhisbug commented on _posts/2019-04-17-lecture-25.md
> +This is much more difficult to fix, and intuitively corresponds to how the problem becomes intractable if $k >> m$.
The indent is missing here. Please fix.

2019-05-06 18:15 UTC, xiamengzhou commented
@zhisbug Updated all the reviews.

2019-05-10 19:58 UTC, alshedivat commented
@zhisbug, are we ready to merge?

2019-05-10 21:43 UTC, merged