Lecture 26: Gaussian processes (GPs) and elements of meta-learning
sailinglab/pgm-spring-2019 pull request #34
Opened 2019-04-30 03:38 UTC by anjalief

https://anjalief.github.io/pgm-spring-2019/notes/lecture/

2019-05-04 17:33 UTC, pliang279 requested changes
hi everyone, please make these small changes, thanks!

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> +$$posterior = \frac{likelihood * prior}{marginal\ likelihood}$$
do \textrm for normal text in math mode

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> +K_{ij} = cov(f(x_i), f(x_j)) = k(x_i, x_j) = 1 + x_bx_c
do \textrm for normal text in math mode

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> +&= a^2 \exp(-\frac{\Vert x-x'\Vert^2}{2\ell^2})
\left( and \right)

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> + * Learning requires a $\log | k_\theta + \sigma^2 \mathbf{I}|$ step,
this does not render correctly

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> +In standard learning, given a distribution over examples (single task), we learn a function that minimizes the loss $\hat \phi = argmin_{\phi} E_{z \sim D}[l(f_{\phi}(z))]$
argmin in \textrm

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> +**Conditional Neural Processes**
add references and expand more, a figure would help

2019-05-04 17:33 UTC, pliang279 commented on _posts/2019-04-26-lecture.md
> +**Attentive Neural Processes**
add references and expand more, a figure would help

2019-05-05 23:47 UTC, anjalief commented
I've made the requested changes to the first third in https://github.com/sailinglab/pgm-spring-2019/pull/34/commits/2e241c5bc31c830112d2418148dd0465add96260

2019-05-10 19:59 UTC, alshedivat commented
@anjalief, @pliang279, can you iterate on this quickly and merge by EOD today? Thanks.

2019-05-10 21:30 UTC, anjalief commented
@pliang279 I've made additional corrections to the lines that didn't render properly in https://github.com/anjalief/pgm-spring-2019/commit/43674d8c0ce06f2e6f9f0da05fb8be1d0fabc6fa

2019-05-10 22:45 UTC, merged