Lecture 28: A Civil Engineering Perspective on AI
sailinglab/pgm-spring-2019 pull request #36
Opened 2019-05-06 19:19 UTC by jmcohen

2019-05-10 19:51 UTC, alshedivat requested changes
Thanks for a great set of notes! Please address the minor requested changes, and we'll be ready to merge. Please do so as soon as possible (end of today is the deadline).

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +  - name: TODO
```suggestion
  - name: Maruan Al-Shedivat
```

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +    url: "#"  # optional URL to the editor's homepage
```suggestion
    url: "https://www.cs.cmu.edu/~mshediva/"
```

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +According to a McKinsey CEO survey in 2018, only 39% of the companies made significant progress in implementing AI applications. Up to 7$ of the companies made no progress.
```suggestion
According to a McKinsey CEO survey in 2018, only 39% of the companies made significant progress in implementing AI applications. Up to 7% of the companies made no progress.
```

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +For example,  Theorem 5 in [this paper](http://davidwd.org/papers/2015_ESSP_AAAI_Final.pdf) proves that the
Please change the reference to `<d-cite></d-cite>` format.

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +Texar is a toolkit for text generation built on these principles.
Please cite Texar using `<d-cite></d-cite>`. Here's a bibtex entry for you:
```
@article{hu2018texar,
  title={Texar: A Modularized, Versatile, and Extensible Toolkit for Text Generation},
  author={Hu, Zhiting and Shi, Haoran and Yang, Zichao and Tan, Bowen and Zhao, Tiancheng and He, Junxian and Wang, Wentao and Qin, Lianhui and Wang, Di and others},
  journal={arXiv preprint arXiv:1809.00794},
  year={2018}
}
```

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +You might have noticed that this year was the first SysML conference (last year's SysML was just a workshop).
Could you link to http://www.sysml.cc/?

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +Interestingly, it's not only the SGD update that's low-rank: the [SDCA](http://www.jmlr.org/papers/volume14/shalev-shwartz13a/shalev-shwartz13a.pdf) update is also low-rank.
Please change the link to `<d-cite></d-cite>` reference.

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +[This paper](http://www.cs.cmu.edu/~pengtaox/papers/uai16_sfb.pdf) provides a detailed analysis of the correctness of this approach.
Please change the link to `<d-cite></d-cite>` reference.

2019-05-10 19:51 UTC, alshedivat commented on _posts/2019-04-29-lecture-28.md
> +Recent work on [contextual explanation networks](https://arxiv.org/abs/1705.10301) allow you to incorporate explanations directly into the model.  Intuitively, you train a “personalized” model for ev
Please change the link to `<d-cite></d-cite>` reference.

2019-05-11 05:52 UTC, jmcohen commented
fixed!

2019-05-11 14:56 UTC, alshedivat approved these changes

2019-05-11 14:56 UTC, merged