Lecture 5: Parameter Estimation in Fully Observed Bayesian Networks
sailinglab/pgm-spring-2019 pull request #5
Opened 2019-02-12 02:48 UTC by celsius38

Hi,
The following is a link to the rendered version:
https://celsius38.github.io/pgm-spring-2019/notes/lecture-05/

Thanks,
Lecture 05 scribing team

2019-02-19 16:15 UTC, alshedivat commented
@zhisbug, can you review this asap?

2019-02-21 18:30 UTC, zhisbug commented
> @zhisbug, can you review this asap? Thanks!

Sure, working on it.

2019-03-03 06:30 UTC, zhisbug requested changes
@celsius38  @muqiaoyang Please address all my comments and I'll take a second look then.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Last class, we presented two major types of graphical model task, **Inference** and **Learning**, and we mainly discussed about inference. In this lecture, we start to introduce learning task, and ex
task -> tasks. 
learning task -> the learning task.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +The goal: Given set of independent samples (assignments of random variables), find the best (or the most likely) Bayesian Network (both DAG and CPDs).
given set of -> given a set of

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +1. completely observed GMs:
Capitalize the first character.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +When doing parameter learning, we assume that the Graphical model **G** itself is known and fixed, G could come from either expert design or an intermediate outcome of iterative structure learning.
Make sure you are consistent on your notation for $G$.
If you bold it then you should keep it bold all over the notes.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +The goal of parameter learning is that we estimate parameters from a dataset of N independent, indentically distributed (iid) training cases $D = \{x_1, ..., x_N\}$.
change N to latex N -> $N$

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +The goal of parameter learning is that we estimate parameters from a dataset of N independent, indentically distributed (iid) training cases $D = \{x_1, ..., x_N\}$.
change to: the goal of parameter learning is to estimate ...

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +The goal of parameter learning is that we estimate parameters from a dataset of N independent, indentically distributed (iid) training cases $D = \{x_1, ..., x_N\}$.
What is "training cases"? maybe "training samples" is more appropriate.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +The goal of parameter learning is that we estimate parameters from a dataset of N independent, indentically distributed (iid) training cases $D = \{x_1, ..., x_N\}$.
iid -> i.i.d.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +In general, each training case $$\mathbf{x}_n = (x_{n,1}, ..., x_{n, M})$$ is a vector of $M$ values, one per node. Depending on the model, elements in $$\mathbf{x}_n$$ could be all known (no missing
use /ldots instead of ...

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +In general, each training case $$\mathbf{x}_n = (x_{n,1}, ..., x_{n, M})$$ is a vector of $M$ values, one per node. Depending on the model, elements in $$\mathbf{x}_n$$ could be all known (no missing
$$\exists i, s.t. x_{n,i}$$ -> $$\exists i, x_{n,i}$$ is not observed (remove s.t. which is not necessary)

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +In this class, we mainly consider learning parameters for a **BN** with given structure and is **completely observable**.
learning parameters for a **BN** with given structure and is **completely observable**.

-> learning parameters for a **BN** that is **completely observable** with a given structure.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +There are various density estimation tasks that can be viewed as single-node GMs (see supplementary section for examples), and they are in fact instances of **Exponential Family Distrubution**.
**Exponential Family Distrubution** -> **Exponential Family Distributions**

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +There are various density estimation tasks that can be viewed as single-node GMs (see supplementary section for examples), and they are in fact instances of **Exponential Family Distrubution**.
see supplementary section -> see the supplementary section.
Please link to the supplementary section as well.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Exponential Family Distrubutions are building blocks for general GM, and have nice properties allowing us to easily do MLE and Bayesian estimation.
Distrubutions -> Distributions

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Exponential Family Distrubutions are building blocks for general GM, and have nice properties allowing us to easily do MLE and Bayesian estimation.
general GM -> general GMs

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +For a numeric random variable $X$,
Please distinguish $X$ and $x$, and random variable from event, and use them in a consistency way.
Here, if the capital $X$ is a random variable (as you have notated), why the lowercase $x$ is used in the equation?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$$p(x|\eta) = h(x)exp\{\eta^T T(x) - A(\eta)\}=\frac{1}{Z(\eta)}h(x)exp\{\eta^T T(x)\}$$
use $/exp$ instead of $exp$

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Function $T(x)$ is a sufficient statistic (will be explained in sufficiency section).
"sufficiency section"? Is it a typo?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +We can see there're lots of probability distributions actually belong to this family (including Bernoulli, Multinomial, Gaussian, Poisson, Gamma).
belong -> belonging

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +For a continuous vector random variable $X\in R^k$:
Still please unify your notation for random variables and events.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$$p(x|\mu,\Sigma) = \frac{1}{(2\pi)^{k/2}|\Sigma|^{1/2}}exp\{-\frac{1}{2}(x-\mu)^T \Sigma^{-1}(x-\mu)\}$$
change $exp$ tp $\exp$ as well here.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Doing this convertion, we change the Moment parameter ($\mu$) into Natural parameter ($\eta$).
No need to capitalize Moment or Natural

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Also note that a $k$-dimensional Gaussian is a ($k$+$k^2$) parameter distribution with a  ($k$+$k^2$) element vector of sufficient statistics (but because of symmetry and positivity, parameters are c
I feel difficult to understand this sentence

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +For a binary vector random variable $x\sim multi(x \vert \pi)$,
we usually don't use $~ multi$. Please complete it as $~ multinomial(*)$

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +**Moment vs canonical parameters**
vs -> vs.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +So we can say that A distribution in the exponential family can be parameterized not only by $\eta$ - the canonical parameterization, but also by $\mu$ - the moment parameterization.
A -> a

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +For iid data, we have the log-likelihood to be
For iid data, we have the log-likelihood to be 
-> For i.i.d. data, we have the log-likelihood:

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Function $T(x)$ is a sufficient statistic (will be explained in sufficiency section).
oops, there does exist a section called sufficiency. Please link to it using anchors.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Then, We can throw away $X$ for the purpose of inference w.r.t $\theta$.
No need to start a newline for each sentence...

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +There are various conditional density estimation tasks that can be viewed as two-node GMs (see supplementary section for examples). Many are instances of Generalized Linear Models.
link to the supplementary section (using anchors.)

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$$E_p(\mathbf{y)} = \mu = f(\theta^T\mathbf{x})$$
and what is $E_p$ denoted for?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +where $\epsilon$ is an error term ofunmodeled effects or random noise.
ofunmodeled? typo?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +We can use LMS algorithm, which is a gradient ascent/descent approach, to estimate the parameter.
LMS algorithm -> the LMS algorithm

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +The condition distribution: a Bernoulli:
-> The condition distribution is a Bernoulli:

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$$p(\mathbf x) = \frac{1}{Z}exp\{ -\sum_{c\in C} \phi_c(\mathbf x_c)\} = \frac{1}{Z}exp\{-H(\mathbf x)\}$$ $$p(X) = \frac{1}{Z}exp\{\sum_{i,j\in N_i}\theta_{ij}X_iX_j+\sum_i\theta_{i0}X_i\}$$
fix $exp$ here.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Discriminative
please expand this single word to be more meaningful.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$$p_\theta(y|x) = \frac{1}{Z(\theta,x)}exp\{\sum_c\theta_cf_c(x,y_c)\}$$
fix $exp$ here.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +\ell = \sum\limits_nlogh(y_n)+\sum\limits_n(\theta^Tx_ny_n-A(\eta_n))
actually, log can also be nicely presented by using $\log$. Give it a try.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +\frac{d\ell}{dt}=\sum_n(x_ny_n-\frac{dA(\eta_n)}{\eta_n}\frac{d\eta}{d\theta})=\sum_nx_n(y_n-\mu_n)=X^T(y-\mu)
what is $t$ here?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Recall that the Hessian matrix $H=-X^TWX$, and $\theta^*=(X^TX)^{-1}X^Ty$ in least mean square optimization, we use Newton-Raphson method with cost function $\ell$ $$\theta^{t+1}=\theta^t-H^{-1}\nabl
This equation seems to be poorly formatted:  $\ell$ $$\theta^{t+1}=\theta^t-H^{-1}\nabla_\theta\ell=(X^TW^tX)^{-1}X^TW^tz^t$$

Did you miss a pair of ()?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +where the response is $z^t=X\theta^t+(W^t)^{-1}(y-\mu^t)$. Hence, this can be understood as solving the Iteratively reweighted least squares problem.
insert a blank newline here.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +\ell(\theta,D)=log p(D|\theta)=\sum_i(\sum_nlogp(x_{n,i}|\mathbf{x_{n,\pi_i},\theta_i}))
$log$ -> $\log$

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +<figure>
what are these two diagrams for? How are they connected with the notes?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Consider a network structure $G$ over a set of variables $X = \{X_1,...,X_n\}$, parameterized by a set of parameters $θ$. Each variable $X_i$ is associated with a CPD $P(X_i | U_i,\theta)$. Now, rath
rather than assume -> rather than assuming

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +If what we observe are continuous, we can treat them as Gaussian, and apply corresponding learning rules for Gaussian.
Missing a blank line here?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +#### Pro
Pros

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +#### Con
Cons

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +m_i(y_1,...,y_{N_i}) = \sum_{x_i \in Val(X_i)} \prod_{j=1}^{k_i} m(x_i, y_{c_i})
Please explain this equation -- the notations, how it is connected to your description above.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Can be viewed as single-node graphical models
I don't understand this sentence. Please revise.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$P(n)=\frac{N!}{n_1!n_2! ... n_k!}\theta^n$
what is $P(n)$ here?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +#### Posterior distribution of \theta
\theta -> $\theta$

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +#### Posterior mean estimation
actually,  you don't have to make every sentence a header with ####. Just use plain text formatting instead.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +#### Posterior mean estimation
Please fix all improper headers

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +### Limitation of Dirichlet Prior
only a figure? Please add descriptions of this figure.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Pro: co-variance structure
Missing a newline here?

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +### Logistic Normal Densities
blank section? either remove it or complete it.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +$P(x)=\frac{1}{b-a}$ for $a\leq x \leq b$
Please reformat this nicely using Latex. The current formatting does look good.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +	* Update estimate sequentially over time
Unsure what this bullet point means? please clarify

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +	a convex combination of sample mean and prior mean, and
is a convex? please complete the full sentence...

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +		$$ P(\mu, \sigma^2| m,V,a,b) = P(\mu | \sigma^2, m, V) P(sigma^2 | a,b) = \mathcal{\mu | m, \sigma^2 V} Gamma(\lambda | a_n, b_n)$$
The equation is a little bit confusing to me. Please fix.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +And by that each $(y_i, x_i$ are i.i.d, we have:
please fix $(y_i, x_i$

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +we notice that maximizing this term w.r.t $\theta$ is equivalent to minimizing a MSE(mean square error):
is equivalent to minimizing a MSE(mean square error):
-> is equivalent to minimizing the MSE (mean square error):

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +"Optimal" means the empoloyed algorithms guaranteed to return a structure that maximizes the objective. Some popluar heuristics, however, provide no gurantee on attaining optimality, interpretability
empoloyed  -> employed

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +"Optimal" means the empoloyed algorithms guaranteed to return a structure that maximizes the objective. Some popluar heuristics, however, provide no gurantee on attaining optimality, interpretability
guaranteed to -> are  guaranteed to

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +"Optimal" means the empoloyed algorithms guaranteed to return a structure that maximizes the objective. Some popluar heuristics, however, provide no gurantee on attaining optimality, interpretability
e.g.: structured, you don't need to append a : after e.g.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +"Optimal" means the empoloyed algorithms guaranteed to return a structure that maximizes the objective. Some popluar heuristics, however, provide no gurantee on attaining optimality, interpretability
Module network -> module network. Please maintain consistency on your capitalization.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +But we can find exact solution of an optimal tree under MLE:
Missing a . here? Please fix.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +Lead to the Chow-Liu Algorithm
Missing a break between two sentences? Please fix all these (minor) formatting issues.

2019-03-03 06:30 UTC, zhisbug commented on _posts/2019-01-30-lecture-05.md
> +	- Direction: pick any node as root, do BFS do define directions
what does "do BFS do define directions" mean?

2019-03-09 21:19 UTC, pliang279 commented
hey everyone, please resolve these changes asap!

2019-03-13 18:39 UTC, celsius38 commented on _posts/2019-01-30-lecture-05.md
> +For a numeric random variable $X$,
Hello. We denote the random variable by capitalized character (e.g.: X), and the specific value it takes as lower-case character (e.g.: x). Formally, it is understood as $p_X(X = x)$

2019-03-14 01:16 UTC, celsius38 commented on _posts/2019-01-30-lecture-05.md
> +<figure>
To illustrate that learning the first graph in the first diagram is like learning four separate small BNs as in the second diagram, each of which consists of a node and its parents.

2019-03-14 02:59 UTC, celsius38 commented
Hello, I think we have fixed the problems you have mentioned. Please check it again. Thanks.

2019-03-14 15:22 UTC, alshedivat commented
Overall, looks good. I fixed a formatting bug for you and added examples of how to use aligned math equations. Can you please reformat some of your math to make equations nicely aligned? Thanks!

I'll let @zhisbug review the rest of the changes.

2019-03-15 04:47 UTC, celsius38 commented
Hello, one quick question. It seems that sometimes, a single dollar bracket doesn't seem to work, e.g.: `$\mathbf{x}_n = (x_{n,1}, \cdots, x_{n, M})$` simply breaks:
![image](https://user-images.githubusercontent.com/12364523/54409150-a3a77480-46bb-11e9-8333-4796bd5dc5b3.png)

When shall we use `$x$` and when `$$x$$`?

2019-03-15 05:05 UTC, alshedivat commented
Hmm, good point, I think single `$` doesn't recognize certain math-mode functions (e.g., in this case it doesn't render because of `mathbf`). I'd recommend using whichever works best, as long as you keep it consistent throughout the notes.

2019-03-20 00:17 UTC, celsius38 commented
Hello. We are ready for review. @zhisbug

2019-03-22 11:28 UTC, zhisbug commented
LGTM, good to merge now.

2019-03-22 16:35 UTC, zhisbug approved these changes

2019-03-22 16:36 UTC, merged