Lecture 7: Maximum likelihood learning of undirected GM
sailinglab/pgm-spring-2019 pull request #7
Opened 2019-02-14 05:35 UTC by danishpruthi

2019-02-15 15:24 UTC, alshedivat commented
Can you edit your first comment and add a link to the rendered version of the notes? Thanks.

2019-02-17 21:15 UTC, tzehuik commented
https://tzehuik.github.io/pgm-spring-2019/notes/lecture-07/

2019-02-19 23:47 UTC, alshedivat requested changes
Please address the comments below and I'll take another look.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Now the question arises if we can follow the sane procedure as for directed graphical Models to find the MLE of an UGM?  The answer is no - we cannot.
```suggestion
Now the question arises if we can follow the same procedure as for directed graphical Models to find the MLE of a UGM?  The answer is no - we cannot.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Separate equations with empty lines to turn them into display mode (or use `<d-math></d-math>` environment).

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +This is a big issue but we still use undirected graphical models as they are useful - They are used to represent some special cases which cannot be represented by directed graphical models alone. The
Please make sure sentences end with correct punctuation.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Here, we introduce two new quantities Total Count and Clique Count.
```suggestion
Here, we introduce two new quantities *Total Count* and *Clique Count*.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Total count for an Undirected Graphical Model (V,E), is simply the number of times that a configuration x (i.e., $X_v=x$) is observed in a dataset $D = \left\{ \mathbf { x } _ { 1 } , \ldots , \mathb
```suggestion
Total count for an Undirected Graphical Model $(V, E)$, is simply the number of times that a configuration $x$ (i.e., $X_v=x$) is observed in a dataset $D = \left\{ \mathbf { x } _ { 1 } , \ldots , \mathbf { x } _ { N } \right\}$
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please use `<d-math></d-math>` for complex math. Otherwise it doesn't display correctly.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Taking the derivative we get,
I don't understand what are these chopped/incomplete sentences. Please fix.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Thus we turn to two important algorithms, what we call workhorse Algorithms.
Please fix all the math in the previous subsection (I recommend using `<d-math></d-math>` for all display equations as done in the further sections below).

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Looks like most of the math in the IPF section doesn't render. Please fix and I'll take another look.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +\psi_c(c_1,c_2,c_3) = e^{\theta_{ing}f_{ing}} \times e^{\theta_{?ed}f_{?ed}} \times ... \\
```suggestion
\psi_c(c_1,c_2,c_3) &= e^{\theta_{ing}f_{ing}} \times e^{\theta_{?ed}f_{?ed}} \times \dots \\
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +  exp\{\sum^K_{k=1}\theta_k f_k(c_1,c_2,c_3)\}
```suggestion
  &= \exp \left\{ \sum^K_{k=1}\theta_k f_k(c_1,c_2,c_3) \right\}
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +\psi_c(c_1,c_2,c_3) \propto exp\{\theta_{ing}f_{ing}(c_1,c_2,c_3) + \theta_{qu?}f_{qu?}(c_1,c_2,c_3) +\theta_{zzz}f_{zzz}(c_1,c_2,c_3) + ... \}
```suggestion
\psi_c(c_1,c_2,c_3) \propto \exp \left\{ \theta_{ing}f_{ing}(c_1,c_2,c_3) + \theta_{qu?}f_{qu?}(c_1,c_2,c_3) +\theta_{zzz}f_{zzz}(c_1,c_2,c_3) + \dots \right\}
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +in general, the features may be overlapping, unconstrained indicators or any function of any subset of the clique variables. For example if you have multiple cliques such as overlapping windows over
```suggestion
In general, the features may be overlapping, unconstrained indicators or any function of any subset of the clique variables. For example, if you have multiple cliques such as overlapping windows over all possible combinations of triplets in our spelling checking example, this does not change the anatomy of the potential, where we still have a weighted sum of the features.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +For example, if we were to look at the consecutive appearance of 3 characters, $c_1, c_2, c_3$, which we represent with the potential function $\psi(x_c)$. The rationale behind this is that we can us
```suggestion
For example, if we were to look at the consecutive appearance of 3 characters, $c_1, c_2, c_3$, which we represent with the potential function $\psi(x_c)$. The rationale behind this is that we can use this to score the likelihood of misspelling. E.g. If we see the sequence 'zyz', we would know that such a sequence does not exist in the English vocabulary and therefore has a very high likelihood of being a misspelling. On the other hand, if we see the sequence 'ink', we know that there are some words which contain this sequence and consequently a lower likelihood of misspelling. This is an example of how the potential can help us do spelling checking. However, if we were to iterate over all the different combinations of triplets in the alphabet, this would imply that we have $26^3$ features, and this gets worse if we increase the size of the sequence. Such a general "tabular" potential function would be exponentially costly for inference and have exponential numbers of parameters that we must learn from limited data, which would exhaust the computer's memory.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +In our earlier example of spelling checking, since we know how frequent certain triplets are based on existing knowledge (e.g. a dictionary or our own vocabulary), we can pick out those we have the g
```suggestion
In our earlier example of spelling checking, since we know how frequent certain triplets are based on the existing knowledge (e.g. a dictionary or our own vocabulary), we can pick out those we have the greatest confidence in and assign them features. Here a feature is defined as a function which is vacuous for most joint settings except a few particular ones, in which it returns either high or low values. E.g. we can define a feature $f_{ing} = 10$ and $f_{ate} = 9$, and so on and so forth. By the time we get to the 50th or 100th feature, we assume that these combinations are less likely and assign them some arbitrary small likelihood of $\alpha$. We can also define features when the inputs are continuous. Then the idea of having a cell on which the feature is active is no longer relevant, but we might still have a compact parameterization of the feature.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Equation didn't render. Please fix.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +_**MLE for undirected graphical models**_:
Can you convert these to proper subsections throughout the text? Use `###` or `####` for sub- or subsub- sections, respectively.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +\tilde{l}(\theta; D) = l(\theta;D)/N = \frac{1}{N}\sum_{n} \log p(x_n \mid \theta) \\
```suggestion
\tilde{l}(\theta; D)
&= \frac{l(\theta;D)}{N} \\
&= \frac{1}{N}\sum_{n} \log p(x_n \mid \theta) \\
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +  = \sum_x \tilde{p}(x)\log p(x \mid \theta) \\
```suggestion
  &= \sum_x \tilde{p}(x)\log p(x \mid \theta) \\
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +  = \sum_x \tilde{p}(x)\sum_i \theta_{i} f_i(x) - \log Z(\theta)
```suggestion
  &= \sum_x \tilde{p}(x)\sum_i \theta_{i} f_i(x) - \log Z(\theta)
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +$$
Please fix math.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +</d-math>
Please fix math alignment.

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Why do we call this scaling? To see this, take a look at the form of the last equation. It is in the form of a ratio calculated over two methods. One is the feature weighted by its empirical probabil
```suggestion
Why do we call this scaling? To see this, take a look at the form of the last equation. It is in the form of a ratio calculated over two methods. One is the feature weighted by its empirical probability, and the other is a feature weighted by the inferred probability. In other words, it's the ratio between what you observe and what you estimate based on what you have now, and we are essentially rescaling the expression iteratively like this.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +On the other hand, GIS is an iterative scaling on general UGM with feature-based potentials. IPF is in fact a special case of GIS in which the clique potential is built on features defined as an indi
```suggestion
On the other hand, GIS is an iterative scaling on general UGM with feature-based potentials. IPF is, in fact, a special case of GIS in which the clique potential is built on features defined as an indicator function of clique configurations.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +These class of distributions come up often in machine learning, and other applications. Some of the most common distributions are exponential. The normal distribution, the exponential distribution, t
```suggestion
These class of distributions come up often in machine learning, and other applications. Some of the most common distributions are exponential. The normal distribution, the exponential distribution, the chi-squared, the bernoulli, the multinomial, the poisson, and even the geometric distribution are all members of the exponential family.
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +    max_p - \sum_{x}p(x)log(p(x)) \\
```suggestion
    \max_p & - \sum_{x}p(x)log(p(x)) \\
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +    s.t. \sum_{x}p(x)f_i(x) = \alpha_i \\
```suggestion
    s.t. & \sum_{x}p(x)f_i(x) = \alpha_i \\
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +    \sum_{x}p(x) = 1 \\
```suggestion
    & \sum_{x}p(x) = 1 \\
```

2019-02-19 23:47 UTC, alshedivat commented on _posts/2019-02-06-lecture-07.md
> +Lastly, a [tutorial](https://people.cs.umass.edu/~mccallum/papers/crf-tutorial.pdf) from Sutton, and McCallum is an excellent resource to know more in-depth details about CRFs
Please convert the reference to a citation (`<d-cite>`).

2019-02-24 23:25 UTC, alshedivat commented
Please let me know when to take another look. You can apply suggested changes in the comments above directly through GitHub.

2019-02-28 08:12 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +Taking the derivative we get,
The equations were not rendering correctly previously. Now resolved.

2019-02-28 08:12 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +Now the question arises if we can follow the sane procedure as for directed graphical Models to find the MLE of an UGM?  The answer is no - we cannot.
Resolved

2019-02-28 08:13 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +$$
Resolved, using <d-math></d-math> uniformly.

2019-02-28 08:13 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +Here, we introduce two new quantities Total Count and Clique Count.
Resolved.

2019-02-28 08:13 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +Total count for an Undirected Graphical Model (V,E), is simply the number of times that a configuration x (i.e., $X_v=x$) is observed in a dataset $D = \left\{ \mathbf { x } _ { 1 } , \ldots , \mathb
Resolved.

2019-02-28 08:13 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +$$
Resolved.

2019-02-28 08:14 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +Thus we turn to two important algorithms, what we call workhorse Algorithms.
Resolved.

2019-02-28 08:14 UTC, rameshrudx commented on _posts/2019-02-06-lecture-07.md
> +$$
Resolved.

2019-02-28 23:38 UTC, danishpruthi commented
@alshedivat: you can have a look now :)

2019-03-13 23:33 UTC, alshedivat approved these changes

2019-03-13 23:35 UTC, merged