Lecture 9: Modeling Networks
sailinglab/pgm-spring-2019 pull request #9
Opened 2019-02-19 20:53 UTC by LlamaSi

Dear Xun,
We've finished our notes, please review. Thanks.

Rendered vesion
[https://llamasi.github.io/pgm-spring-2019/notes/lecture-09/](url)

2019-02-20 20:02 UTC, xunzheng requested changes

2019-02-20 20:02 UTC, xunzheng commented on _posts/2019-02-13-lecture-09.md
> +### Why this algorithm work?
```suggestion
### Why does this algorithm work?
```

2019-02-20 20:02 UTC, xunzheng commented on _posts/2019-02-13-lecture-09.md
> +  $$p(x_1|x_2) = \mathcal{N}(x_2 | \mu_{1|2}, V_{1|2}) $$
```suggestion
  $$p(x_1|x_2) = \mathcal{N}(x_1 | \mu_{1|2}, V_{1|2}) $$
```

2019-02-21 01:32 UTC, LlamaSi commented
Can we merge now? Sorry but I'm not familiar with this process.

2019-02-21 01:38 UTC, alshedivat commented
Some additional comments:
- Editor's name.
- Title of the notes is duplicated.
- Everything before section "GGM with Lasso" seems to be just a list of bullet points. Can you convert that to proper notes?
- References must be added using `<d-cite>` instead of links (see the template for examples).

2019-02-21 04:05 UTC, LlamaSi commented
> Some additional comments:
> 
> * Editor's name.
> * Title of the notes is duplicated.
> * Everything before section "GGM with Lasso" seems to be just a list of bullet points. Can you convert that to proper notes?
> * References must be added using `<d-cite>` instead of links (see the template for examples).

Thanks for the advice. Please see the committed modification.

2019-02-21 16:37 UTC, xunzheng approved these changes

2019-02-21 16:37 UTC, merged